task-1
qsqnk/high-performance-graph-analysis-course pull request #1
Opened 2023-03-11 17:29 UTC by qsqnk

# Задача 1. Реализация обхода в ширину (BFS – LEVELS)

* **Мягкий дедлайн**: 12.03.2023, 23:59
* **Жёсткий дедлайн**: 15.03.2023, 23:59
* Полный балл: 5

## Подготовка
- [x] Сделать публичный `fork` данного репозитория.
- [x] Добавить ссылку на ваш `fork` в [таблицу](https://docs.google.com/spreadsheets/d/1VAfnSGd63GulSdig8TLISOXBF7MMIUm3egO4U_jdugI/edit?usp=sharing).
- [x] Добавить в совладельцы форка одного из ассистентов (чтобы узнать, кого именно, нужно посмотреть в [таблицу](https://docs.google.com/spreadsheets/d/1VAfnSGd63GulSdig8TLISOXBF7MMIUm3egO4U_jdugI/edit?usp=sharing))

## Задача

Везде считаем, что вершины графа занумерованы подряд с нуля.

- [x] Используя pygraphblas реализовать функцию обхода ориентированного графа в ширину из заданной вершины. При этом организовать все вычисления в виде операций над векторами и матрицами.
  - [x] Функция принимает представление графа, удобное для неё (загрузка, конвертация реализованы отдельно) и номер стартовой вершины.
  - [x] Функция возвращает массив, где для каждой вершины указано, на каком шаге она достижима. Стартовая вершина достижима на нулевом шаге, если вершина не достижима, то значение соответствующей ячейки равно -1.
- [x] Добавить необходимые тесты.
- [x] Добавить запуск тестов с помощью `pytest` в `.github/workflows/`.
    - Проверить, что тесты запускаются только на linux.

2023-03-14 09:50 UTC, rustam-azimov requested changes

2023-03-14 09:50 UTC, rustam-azimov commented on project/bfs.py
> +        used |= level
Можно обойтись без used. Просто проверяем не пустой ли фронт (у Вас это level), если не пустой - продолжаем. Вместо маски used можно использовать ans.

2023-03-14 09:50 UTC, rustam-azimov commented on project/bfs.py
> +        level @= graph
Лучше сразу вызвать функцию умножения с маской нужной. Иначе теряется смысл, мы хотим лишнее не считать.

2023-03-14 09:50 UTC, rustam-azimov commented on tests/test_bfs.py
> +    [
Лучше сразу реализовать функции считывания графов с файла например и конвертации в нужный формат.

2023-03-15 11:52 UTC, qsqnk commented
Всё поправил

2023-03-18 07:04 UTC, rustam-azimov approved these changes
5 баллов

2023-03-18 09:00 UTC, merged